董创轼week1
CDDSCLab/training-plan pull request #21
Opened 2020-07-10 16:32 UTC by dongcss

### What problem does this PR solve?

### What have you done or changed in this PR?

### What test did you complete before submitting the PR?

2020-07-12 17:24 UTC, karmanluo reviewed
Line 305, Need change local picture path to network path.

2020-07-12 17:24 UTC, ehds requested changes

2020-07-12 17:24 UTC, ehds commented on Week1-Database-Introduction/DongChuangshi-Week1/董创轼实验报告.md
> +8、
增加 8 的说明

2020-07-12 17:24 UTC, ehds commented on Week1-Database-Introduction/DongChuangshi-Week1/董创轼实验报告.md
> +3、
增加 3 后的说明 `加载图出错`

2020-07-13 06:06 UTC, ehds approved these changes

2020-07-13 06:07 UTC, ehds commented
> Line 305, Need change local picture path to network path.

你在review的时候可以直接标记位置。

2020-07-13 11:42 UTC, ehds commented on Week1-Database-Introduction/DongChuangshi-Week1/董创轼实验报告.md
> +[graph-of-the-gods](https://github.com/dongcss/training-plan/blob/master/images/graph-of-the-gods-2.png)
add `!` before `[graph-of-the-gods]`.

2020-07-23 08:06 UTC, karmanluo approved these changes
LGTM

2021-01-13 15:56 UTC, closed without merging