Ztyweek2
CDDSCLab/training-plan pull request #44
Opened 2021-09-21 20:08 UTC by ztygreat

### What problem does this PR solve?

### What have you done or changed in this PR?

### What test did you complete before submitting the PR?

2021-09-24 06:48 UTC, ehds requested changes

2021-09-24 06:48 UTC, ehds commented on Week2-Data-Structure-I/ztywork/src/BloomFilter/bloomfilter.cpp
> +bool BloomFilter::Hash(std::string key){
永远为true，没必要将函数返回值设置为bool

2021-09-24 06:48 UTC, ehds commented on Week2-Data-Structure-I/ztywork/src/BloomFilter/bloomfilter.cpp
> +    if(!Hash(key))
不必要的判断，永远为true

2021-09-24 06:48 UTC, ehds commented on Week2-Data-Structure-I/ztywork/src/BloomFilter/bloomfilter.cpp
> +bool BloomFilter::contains(std::string key){
const std::string &key

2021-09-24 06:48 UTC, ehds commented on Week2-Data-Structure-I/ztywork/src/BloomFilter/bloomfilter.cpp
> +bool BloomFilter::Hash(std::string key){
const std::string &key

2021-09-24 06:48 UTC, ehds commented on Week2-Data-Structure-I/ztywork/src/BloomFilter/main.cpp
> +int main()
测试代码最好使用测试框架，例如googletest

2021-09-24 06:48 UTC, ehds commented on Week2-Data-Structure-I/ztywork/src/BloomFilter/main.cpp
> +        bloom.add(key);
仅仅是加入key，没有判断key是不是contains，可以增加相关用例。

2021-09-26 01:21 UTC, ztygreat commented on Week2-Data-Structure-I/ztywork/src/BloomFilter/bloomfilter.cpp
> +bool BloomFilter::Hash(std::string key){
因为这个函数会将生成的哈希值存储在成员变量中，所有返回值没有设置成const std::string &key，又不想用void，便设置成了bool

2021-09-26 01:23 UTC, ztygreat commented on Week2-Data-Structure-I/ztywork/src/BloomFilter/main.cpp
> +int main()
ok

2021-09-26 07:20 UTC, CkTD approved these changes

2021-09-26 07:20 UTC, CkTD commented on Week2-Data-Structure-I/ztywork/src/BloomFilter/bloomfilter.h
> +#define TABLE_SIZE 1048576 //32768*4*8
这个为什么是固定的？可以设置成参数

2021-09-26 07:20 UTC, CkTD commented on Week2-Data-Structure-I/ztywork/src/BloomFilter/bloomfilter.cpp
> +bool BloomFilter::add(std::string key){
有没有考虑过容量的问题？ 如果加入的key太多，查询时判断出错的概率怎么保证？

2021-09-26 08:36 UTC, ehds commented on Week2-Data-Structure-I/ztywork/src/BloomFilter/bloomfilter.cpp
> +bool BloomFilter::Hash(std::string key){
我是说的传入的参数key

2021-09-26 08:37 UTC, ztygreat commented on Week2-Data-Structure-I/ztywork/src/BloomFilter/bloomfilter.cpp
> +bool BloomFilter::Hash(std::string key){
哦哦

2021-09-26 15:39 UTC, ehds commented
https://github.com/CDDSCLab/training-plan/discussions/55

2022-10-25 02:35 UTC, closed without merging